import React from 'react';
import { AlertTriangle, ArrowLeft, BadgeCheck, BookOpenCheck, CheckCircle2, ClipboardCheck, Database, ExternalLink, FileWarning, Scale, ShieldAlert, UserCheck } from 'lucide-react';
import { withBasePath } from '../lib/routes';
import PageNavigation, { pageNavigationAsideClassName } from './PageNavigation';

const factors = ['招生名額與實際招生學校科別', '報名人數、考生整體表現與志願填寫情形', '各就學區超額比序與同分比序規則', '身分資格、加分、優先／特殊入學等個別條件', '簡章修訂、時程異動或其他主管機關公告'];

const checkList = ['確認所屬就學區與報名資格。', '依成績通知單核對五科等級、標示與寫作級分。', '查閱目標校科的當年度招生簡章、招生名額及比序規則。', '確認學校類型、科別、交通、學費與個人就讀意願。', '必要時向國中輔導老師、招生委員會或目標學校進一步確認。'];

export default function DisclaimerPage() {
  return <main className="disclaimer-page min-h-screen overflow-x-clip bg-slate-50 text-slate-900">
    <section className="border-b-4 border-slate-900 bg-slate-900 text-white"><div className="mx-auto max-w-6xl px-4 py-5 sm:px-6 lg:px-8"><a href={withBasePath('/')} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-3 py-2 text-sm font-black text-slate-900 shadow-[2px_2px_0_#fbbf24] transition hover:-translate-y-0.5 sm:px-4"><ArrowLeft className="h-4 w-4" />返回首頁</a><div className="grid gap-8 py-10 lg:grid-cols-[1fr_310px] lg:items-end"><div><div className="mb-5 inline-flex items-center gap-3 rounded-2xl border-2 border-white/30 bg-white/10 px-4 py-3"><div className="rounded-xl border-2 border-slate-900 bg-amber-300 p-2 text-slate-900"><Scale className="h-6 w-6" /></div><div><p className="text-xs font-black tracking-widest text-amber-200">IMPORTANT NOTICE</p><p className="text-sm font-black text-slate-200">使用分析前請先閱讀</p></div></div><h1 className="text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">免責聲明</h1><p className="mt-5 max-w-3xl text-base font-bold leading-8 text-slate-200 sm:text-lg">TW 全國會考落點分析系統提供升學規劃與校科比較的輔助資訊，不是政府機關、招生委員會、學校或正式分發系統。請在理解下列限制後使用本服務。</p></div><div className="rounded-2xl border-4 border-amber-300 bg-amber-100 p-5 text-slate-900 shadow-[5px_5px_0_rgba(255,255,255,0.22)]"><p className="text-sm font-black text-amber-800">最重要的原則</p><p className="mt-2 text-xl font-black leading-8">錄取資格、招生名額、比序與時程，一律以當學年度官方簡章及公告為準。</p></div></div></div></section>
    <section className="mx-auto grid max-w-6xl gap-6 px-4 py-8 sm:px-6 sm:py-10 lg:grid-cols-[240px_1fr] lg:px-8"><aside className={pageNavigationAsideClassName}><PageNavigation navClassName="rounded-2xl border-4 border-slate-900 bg-white p-4 shadow-[4px_4px_0_#0f172a]" items={[{ id: 'purpose', label: '服務定位' }, { id: 'limits', label: '分析與資料限制' }, { id: 'responsibility', label: '使用者應確認事項' }, { id: 'privacy', label: '資料與隱私' }, { id: 'official', label: '官方資訊來源' }]} /></aside><div className="min-w-0 space-y-6">
      <section id="purpose" className="scroll-mt-8 rounded-2xl border-4 border-slate-900 bg-white p-5 shadow-[5px_5px_0_#0f172a] sm:p-7"><div className="flex items-start gap-4"><div className="rounded-xl border-2 border-slate-900 bg-sky-100 p-3"><BookOpenCheck className="h-7 w-7 text-sky-700" /></div><div><h2 className="text-2xl font-black sm:text-3xl">一、服務定位與適用範圍</h2><p className="mt-4 text-sm font-bold leading-8 text-slate-700 sm:text-base">本站依使用者輸入的成績、就學區與偏好，呈現校科搜尋、落點比較、志願規劃與相關說明。這些內容的目的，是協助使用者整理資訊與討論選項；本站不辦理報名、不審查資格、不執行分發，也不代替學校輔導、招生單位諮詢或其他專業意見。</p></div></div></section>
      <section id="limits" className="scroll-mt-8"><div className="mb-4"><h2 className="text-2xl font-black sm:text-3xl">二、分析結果與資料限制</h2><p className="mt-2 text-sm font-bold leading-7 text-slate-600">分析結果是依當下可用資料及輸入條件產生的參考資訊，並非對未來錄取結果的預測承諾。</p></div><div className="grid gap-4"><article className="rounded-2xl border-4 border-slate-900 bg-white p-5 shadow-[4px_4px_0_#0f172a]"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border-2 border-slate-900 bg-rose-100"><ShieldAlert className="h-6 w-6 text-rose-700" /></div><div><h3 className="text-xl font-black">不保證錄取或資格</h3><p className="mt-2 text-sm font-bold leading-7 text-slate-700">推薦清單、歷年分數、分數區間、排序、落點標示及其他分析文字，均不構成錄取保證、招生資格認定、報名資格確認或對招生結果的承諾。</p></div></div></article><article className="rounded-2xl border-4 border-slate-900 bg-white p-5 shadow-[4px_4px_0_#0f172a]"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border-2 border-slate-900 bg-amber-100"><AlertTriangle className="h-6 w-6 text-amber-700" /></div><div><h3 className="text-xl font-black">實際結果可能因多項因素不同</h3><p className="mt-2 text-sm font-bold leading-7 text-slate-700">下列因素都可能改變實際招生與分發結果：</p><ul className="mt-3 grid gap-2 sm:grid-cols-2">{factors.map((factor) => <li key={factor} className="flex gap-2 text-sm font-bold leading-6 text-slate-700"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-amber-500" />{factor}</li>)}</ul></div></div></article><article className="rounded-2xl border-4 border-slate-900 bg-white p-5 shadow-[4px_4px_0_#0f172a]"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border-2 border-slate-900 bg-indigo-100"><FileWarning className="h-6 w-6 text-indigo-700" /></div><div><h3 className="text-xl font-black">資料可能更新、修正或暫時無法提供</h3><p className="mt-2 text-sm font-bold leading-7 text-slate-700">本站會持續整理功能與資料，但無法保證所有資料在任何時間都完整、即時或不含錯誤。若官方公告與本站內容不一致，應以官方公告為準；若發現問題，歡迎透過回報功能通知我們。</p></div></div></article></div></section>
      <section id="responsibility" className="scroll-mt-8 rounded-2xl border-4 border-slate-900 bg-sky-100 p-5 shadow-[5px_5px_0_#0f172a] sm:p-7"><div className="flex items-center gap-3"><ClipboardCheck className="h-8 w-8 text-sky-800" /><h2 className="text-2xl font-black sm:text-3xl">三、使用者在選填前應確認的事項</h2></div><p className="mt-3 text-sm font-bold leading-7 text-slate-700">選校與填志願的最終決定由使用者自行作成，建議至少完成以下核對：</p><ol className="mt-5 grid gap-3 sm:grid-cols-2">{checkList.map((item, index) => <li key={item} className="flex gap-3 rounded-xl border-2 border-slate-900 bg-white p-4 text-sm font-bold leading-7"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border-2 border-slate-900 bg-amber-300 font-black">{index + 1}</span>{item}</li>)}</ol></section>
      <section id="privacy" className="scroll-mt-8 rounded-2xl border-4 border-slate-900 bg-white p-5 shadow-[5px_5px_0_#0f172a] sm:p-7"><div className="flex items-center gap-3"><Database className="h-7 w-7 text-emerald-700" /><h2 className="text-2xl font-black sm:text-3xl">四、輸入資料與隱私提醒</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2"><p className="text-sm font-bold leading-8 text-slate-700">請只輸入分析需要的資料，例如就學區、偏好與會考成績。請勿輸入姓名、身分證字號、准考證號、住址、電話或其他與分析無關的個人資料。</p><p className="text-sm font-bold leading-8 text-slate-700">本站對瀏覽器儲存與資料處理的說明，請參閱隱私權政策。請自行妥善保管匯出檔、截圖與邀請碼，避免在不受信任的場合公開。</p></div><a href={withBasePath('/privacy')} className="mt-5 inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-emerald-100 px-4 py-3 text-sm font-black shadow-[2px_2px_0_#0f172a]">查看隱私權政策 <ExternalLink className="h-4 w-4" /></a></section>
      <section id="official" className="scroll-mt-8 rounded-2xl border-4 border-slate-900 bg-amber-300 p-5 shadow-[5px_5px_0_#0f172a] sm:p-7"><div className="flex items-center gap-3"><UserCheck className="h-7 w-7 text-amber-900" /><h2 className="text-2xl font-black sm:text-3xl">五、官方資訊優先與查閱方式</h2></div><p className="mt-4 text-sm font-bold leading-8 text-slate-800">高級中等學校與五專的招生簡章、實際招生名額、日程及作業規則會依招生區、學制與年度不同而有差異。填志願前，請使用所屬招生區的官方網站與目標學校公告逐項核對。</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><a href="https://ws.moe.edu.tw/Download.ashx?icon=..pdf&n=77yI6ZmE6KGoMu%2B8iTExNeWtuOW5tOW6pumrmOe0muS4reetieWtuOagoeWFjeippuWFpeWtuOmHjeimgeaXpeeoi%2BihqC5wZGY%3D&u=LzAwMS9VcGxvYWQvMS9yZWxmaWxlLzc2MzIvMTAzNjMyL2IwZTgzZTZiLWU4ZGItNDJjMi1iYmU3LTliYWFjZmQxODQxMi5wZGY%3D" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border-2 border-slate-900 bg-white p-4 text-sm font-black shadow-[2px_2px_0_#0f172a]">教育部：115 學年度重要日程表 <ExternalLink className="h-4 w-4" /></a><a href="https://www.techadmi.edu.tw/bbs-detail.php?gid=480&nid=1139" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border-2 border-slate-900 bg-white p-4 text-sm font-black shadow-[2px_2px_0_#0f172a]">技專招策會：五專招生簡章資訊 <ExternalLink className="h-4 w-4" /></a></div><p className="mt-5 text-sm font-bold leading-7 text-slate-800">本頁是使用提醒與資訊導覽，不構成法律、教育、升學或其他專業意見。若你不同意本頁所述使用原則，請停止使用本站分析功能。</p></section>
    </div></section>
  </main>;
}
