import React, { useMemo, useState } from 'react';
import { ArrowLeft, Check, CircleDollarSign, FileText, Heart, Info, Mail, Sparkles } from 'lucide-react';
import { withBasePath } from '../lib/routes';

const suggestedAmounts = [50, 100, 300, 500];
const supportEmail = 'tyctw.analyze@gmail.com';

export default function SupportPage() {
  const [selectedAmount, setSelectedAmount] = useState(100);
  const [customAmount, setCustomAmount] = useState('');
  const [notice, setNotice] = useState('');
  const amount = useMemo(() => {
    const value = Number(customAmount);
    return customAmount !== '' && Number.isFinite(value) ? value : selectedAmount;
  }, [customAmount, selectedAmount]);

  const selectAmount = (value: number) => { setSelectedAmount(value); setCustomAmount(''); setNotice(''); };
  const handleSupport = () => {
    if (!Number.isInteger(amount) || amount < 1) { setNotice('請輸入至少 NT$ 1 的支持金額。'); return; }
    setNotice(`已記下您想支持 NT$ ${amount.toLocaleString()}；金流服務開通後，將可在此直接完成付款。`);
  };

  return <main className="min-h-screen bg-slate-50 text-slate-900">
    <section className="overflow-hidden border-b-4 border-slate-900 bg-rose-50"><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8">
      <a href={withBasePath('/')} className="inline-flex items-center gap-2 rounded-xl border-2 border-slate-900 bg-white px-4 py-2 text-sm font-black shadow-[3px_3px_0px_0px_rgba(15,23,42,1)] transition hover:-translate-y-0.5 hover:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] active:translate-y-0 active:shadow-none"><ArrowLeft className="h-4 w-4" /> 回到首頁</a>
      <div className="relative py-12 sm:py-16"><div className="pointer-events-none absolute -right-8 top-2 h-40 w-40 rounded-full border-4 border-slate-900 bg-amber-300 opacity-80 sm:right-16" /><div className="relative max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border-2 border-slate-900 bg-white px-3 py-1.5 text-xs font-black shadow-[3px_3px_0px_0px_rgba(15,23,42,1)]"><Heart className="h-4 w-4 fill-rose-500 text-rose-500" /> SUPPORT OUR WORK</div><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">讓每一次選擇，<br />都有更可靠的方向</h1><p className="mt-5 max-w-2xl text-base font-bold leading-8 text-slate-700 sm:text-lg">我們希望把複雜的升學資訊整理得更清楚、更容易使用。您的一點支持，會成為資料更新、工具優化與免費服務持續運作的穩定力量。</p><p className="mt-3 max-w-2xl text-sm font-bold leading-7 text-slate-600">不論是 NT$ 50，或只是把這個工具分享給需要的人，都能讓更多學生與家長在關鍵時刻少一些焦慮、多一點把握。</p></div></div>
    </div></section>
    <section className="mx-auto grid max-w-6xl gap-7 px-4 py-10 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8">
      <section className="rounded-3xl border-4 border-slate-900 bg-white p-5 shadow-[7px_7px_0px_0px_rgba(15,23,42,1)] sm:p-8"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border-2 border-slate-900 bg-rose-200 shadow-[2px_2px_0px_0px_rgba(15,23,42,1)]"><CircleDollarSign className="h-6 w-6 text-rose-700" /></div><div><p className="text-xs font-black tracking-widest text-rose-700">SMALL SUPPORT, REAL IMPACT</p><h2 className="mt-1 text-2xl font-black sm:text-3xl">選擇一份剛剛好的支持</h2><p className="mt-1 text-sm font-bold text-slate-600">每筆支持皆為一次性自願支持，不會自動續訂或定期扣款。</p></div></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4">{suggestedAmounts.map((value) => <button key={value} type="button" onClick={() => selectAmount(value)} className={`rounded-2xl border-2 border-slate-900 px-3 py-4 text-lg font-black transition ${customAmount === '' && selectedAmount === value ? 'bg-amber-300 shadow-[3px_3px_0px_0px_rgba(15,23,42,1)] -translate-y-0.5' : 'bg-white hover:bg-amber-50'}`}>NT$ {value}</button>)}</div><label className="mt-5 block"><span className="text-sm font-black">自訂金額</span><div className="mt-2 flex items-center rounded-2xl border-2 border-slate-900 bg-slate-50 px-4 focus-within:ring-4 focus-within:ring-amber-300/40"><span className="font-black text-slate-500">NT$</span><input type="number" min="1" inputMode="numeric" value={customAmount} onChange={(event) => { setCustomAmount(event.target.value); setNotice(''); }} placeholder="輸入您想支持的金額" className="w-full bg-transparent px-3 py-4 font-black outline-none" /></div></label><button type="button" onClick={handleSupport} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl border-4 border-slate-900 bg-rose-500 px-5 py-4 text-lg font-black text-white shadow-[5px_5px_0px_0px_rgba(15,23,42,1)] transition hover:-translate-y-0.5 hover:bg-rose-600 active:translate-y-0 active:shadow-none"><Heart className="h-5 w-5 fill-current" /> 支持 NT$ {Number.isFinite(amount) && amount > 0 ? amount.toLocaleString() : '—'}</button>{notice && <p role="status" className="mt-5 rounded-2xl border-2 border-emerald-700 bg-emerald-50 p-4 text-sm font-bold leading-6 text-emerald-900"><Check className="mr-2 inline h-4 w-4" />{notice}</p>}<div className="mt-5 flex items-start gap-2 rounded-2xl border-2 border-sky-200 bg-sky-50 p-4 text-sm font-bold leading-6 text-slate-700"><Info className="mt-0.5 h-5 w-5 shrink-0 text-sky-700" /><p>付款功能尚在準備中：目前不會收集付款資料、不會扣款，也不會建立訂單。金流開通後，將在結帳前清楚顯示收款資訊與付款規則。</p></div></section>
      <aside className="space-y-5"><section className="rounded-3xl border-4 border-slate-900 bg-indigo-600 p-6 text-white shadow-[7px_7px_0px_0px_rgba(245,158,11,1)] sm:p-7"><Sparkles className="h-8 w-8 text-amber-300" /><h2 className="mt-4 text-2xl font-black">這份支持，會走到哪裡？</h2><p className="mt-2 text-sm font-bold leading-6 text-indigo-100">我們會把資源優先用在真正幫助使用者做決定的地方：</p><ul className="mt-5 space-y-3 text-sm font-bold leading-6 text-indigo-100"><li className="flex gap-2"><Check className="h-5 w-5 shrink-0 text-amber-300" />持續校對、更新升學與選校資訊</li><li className="flex gap-2"><Check className="h-5 w-5 shrink-0 text-amber-300" />改善分析工具的準確性、速度與操作體驗</li><li className="flex gap-2"><Check className="h-5 w-5 shrink-0 text-amber-300" />維持核心功能免費，讓需要的人都能使用</li></ul></section><section className="rounded-3xl border-4 border-slate-900 bg-white p-6 shadow-[6px_6px_0px_0px_rgba(15,23,42,1)]"><FileText className="h-7 w-7 text-indigo-700" /><h2 className="mt-3 text-xl font-black">透明，是支持的前提</h2><p className="mt-2 text-sm font-bold leading-6 text-slate-600">付款前請先閱讀售後服務、退款與取消規則。</p><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2"><a href={withBasePath('/after-sales-service')} className="inline-flex min-h-12 items-center justify-center rounded-xl border-2 border-slate-900 bg-white px-4 py-3 text-center text-sm font-black shadow-[3px_3px_0px_0px_rgba(15,23,42,1)] transition hover:-translate-y-0.5 hover:bg-slate-50 hover:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] active:translate-y-0 active:shadow-none">售後服務</a><a href={withBasePath('/refund-cancellation-policy')} className="inline-flex min-h-12 items-center justify-center rounded-xl border-2 border-slate-900 bg-amber-300 px-4 py-3 text-center text-sm font-black shadow-[3px_3px_0px_0px_rgba(15,23,42,1)] transition hover:-translate-y-0.5 hover:bg-amber-400 hover:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] active:translate-y-0 active:shadow-none">退款與取消政策</a></div></section><section className="rounded-3xl border-4 border-slate-900 bg-amber-100 p-6 shadow-[6px_6px_0px_0px_rgba(15,23,42,1)]"><Mail className="h-7 w-7 text-rose-700" /><h2 className="mt-3 text-xl font-black">小額支持聯繫方式</h2><p className="mt-2 text-sm font-bold leading-6 text-slate-700">付款、退款或支持方案相關問題，請來信聯絡，我們會協助處理。</p><a href={`mailto:${supportEmail}?subject=%E9%97%9C%E6%96%BC%E5%B0%8F%E9%A1%8D%E6%94%AF%E6%8C%81`} className="mt-4 inline-flex w-full items-center justify-center gap-2 break-all rounded-xl border-2 border-slate-900 bg-white px-3 py-3 text-sm font-black text-rose-700 shadow-[3px_3px_0px_0px_rgba(15,23,42,1)] transition hover:-translate-y-0.5 hover:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] active:translate-y-0 active:shadow-none"><Mail className="h-4 w-4 shrink-0" />{supportEmail}</a></section></aside>
    </section>
    <section className="mx-auto hidden max-w-6xl items-center gap-6 px-4 pb-10 sm:px-6 lg:flex lg:px-8"><div className="flex flex-1 items-start gap-4 rounded-3xl border-4 border-slate-900 bg-white p-6 shadow-[6px_6px_0px_0px_rgba(15,23,42,1)]"><FileText className="mt-0.5 h-7 w-7 shrink-0 text-indigo-700" /><div><h2 className="text-xl font-black">透明，是支持的前提</h2><p className="mt-2 text-sm font-bold leading-6 text-slate-600">付款前請先閱讀售後服務、退款與取消規則。</p></div><div className="ml-auto flex shrink-0 gap-3"><a href={withBasePath('/after-sales-service')} className="inline-flex min-h-12 items-center justify-center rounded-xl border-2 border-slate-900 bg-white px-4 py-3 text-sm font-black shadow-[3px_3px_0px_0px_rgba(15,23,42,1)] transition hover:-translate-y-0.5 hover:bg-slate-50 hover:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] active:translate-y-0 active:shadow-none">售後服務</a><a href={withBasePath('/refund-cancellation-policy')} className="inline-flex min-h-12 items-center justify-center rounded-xl border-2 border-slate-900 bg-amber-300 px-4 py-3 text-sm font-black shadow-[3px_3px_0px_0px_rgba(15,23,42,1)] transition hover:-translate-y-0.5 hover:bg-amber-400 hover:shadow-[4px_4px_0px_0px_rgba(15,23,42,1)] active:translate-y-0 active:shadow-none">退款與取消政策</a></div></div></section>
    <style>{`@media (max-width: 639px) { div:has(> a[href$="/after-sales-service"]):has(> a[href$="/refund-cancellation-policy"]) { grid-template-columns: repeat(2, minmax(0, 1fr)); } } @media (min-width: 1024px) { aside > section:has(a[href$="/after-sales-service"]):has(a[href$="/refund-cancellation-policy"]) { display: none; } }`}</style>
    <style>{`@media (max-width: 639px) { main > section > aside.space-y-5 { display: flex; flex-direction: column; gap: 1.25rem; } main > section > aside.space-y-5 > :not([hidden]) ~ :not([hidden]) { margin-top: 0; margin-bottom: 0; } main > section > aside.space-y-5 > section:nth-of-type(2) { order: 3; } main > section > aside.space-y-5 > section:nth-of-type(3) { order: 2; } }`}</style>
    <style>{`main > section:first-child .pointer-events-none.absolute { display: flex; align-items: center; justify-content: center; border-radius: 2rem; background: #fbbf24; opacity: 1; box-shadow: 5px 5px 0 #0f172a; transform: rotate(-8deg); } main > section:first-child .pointer-events-none.absolute::before { position: absolute; inset: 20px; border: 3px solid #0f172a; border-radius: 1.15rem; background: #fffaf0; content: ''; } main > section:first-child .pointer-events-none.absolute::after { position: relative; z-index: 1; color: #e11d48; content: '♥'; font-size: 4.5rem; font-weight: 900; line-height: 1; text-shadow: 2px 2px 0 #0f172a; } @media (max-width: 639px) { main > section > aside.space-y-5 { display: flex; flex-direction: column; gap: 1.25rem; } main > section > aside.space-y-5 > :not([hidden]) ~ :not([hidden]) { margin-top: 0; margin-bottom: 0; } main > section > aside.space-y-5 > section:nth-of-type(2) { order: 3; } main > section > aside.space-y-5 > section:nth-of-type(3) { order: 2; } }`}</style>
  </main>;
}
